"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
var core_1 = require('@angular/core');
var KeyboardService = (function () {
    function KeyboardService() {
        this.KEYS = {
            // Special Keys
            CTRL: false,
            SHIFT: false,
            ALT: false,
            MB_L: 1,
            MB_R: 2,
            MB_C: 4,
            BACK: 8,
            TAB: 9,
            CLEAR: 12,
            ENTER: 13,
            //SHIFT:    16,
            //CTRL:     17,
            //ALT:      18,
            PAUSE: 19,
            CAPS: 20,
            HANGUL: 21,
            HANJA: 25,
            ESCAPE: 27,
            SPACE: 32,
            PAGEDOWN: 33,
            PAGEUP: 34,
            HOME: 35,
            END: 36,
            LEFT: 37,
            UP: 38,
            RIGHT: 39,
            DOWN: 40,
            SELECT: 41,
            EXECUTE: 43,
            SNAPSHOT: 44,
            INSERT: 45,
            SUPR: 46,
            HELP: 47,
            // Numeric
            0: 48,
            1: 49,
            2: 50,
            3: 51,
            4: 52,
            5: 53,
            6: 54,
            7: 55,
            8: 56,
            9: 57,
            // Regular keys:
            A: 65,
            B: 66,
            C: 67,
            D: 68,
            E: 69,
            F: 70,
            G: 71,
            H: 72,
            I: 73,
            J: 74,
            K: 75,
            L: 76,
            M: 77,
            N: 78,
            O: 79,
            P: 80,
            Q: 81,
            R: 82,
            S: 83,
            T: 84,
            U: 85,
            V: 86,
            W: 87,
            X: 88,
            Y: 89,
            Z: 90,
            APPS: 93,
            // Num pad
            Num_0: 96,
            Num_1: 97,
            Num_2: 98,
            Num_3: 99,
            Num_4: 100,
            Num_5: 101,
            Num_6: 102,
            Num_7: 103,
            Num_8: 104,
            Num_9: 105,
            MULTIPLY: 106,
            ADD: 107,
            SEP: 108,
            SUB: 109,
            DECIMAL: 110,
            DEVIDE: 111,
            // Functions keys
            F1: 112,
            F2: 113,
            F3: 114,
            F4: 115,
            F5: 116,
            F6: 117,
            F7: 118,
            F8: 119,
            F9: 120,
            F10: 121,
            F11: 122,
            F12: 123,
            F13: 124,
            F14: 125,
            F15: 126,
            F16: 127,
            F17: 128,
            F18: 129,
            F19: 130,
            F20: 131,
            F21: 132,
            F22: 133,
            F23: 134,
            F24: 135,
            NUM: 144,
            SCROLL: 145,
            ';': 186,
            '=': 187,
            ',': 188,
            '-': 189,
            '.': 190,
            '/': 191,
            '`': 192,
            '[': 219,
            '\\': 220,
            ']': 221,
            '\'': 222
        };
    }
    KeyboardService = __decorate([
        core_1.Injectable(), 
        __metadata('design:paramtypes', [])
    ], KeyboardService);
    return KeyboardService;
}());
exports.KeyboardService = KeyboardService;
//# sourceMappingURL=keyboard.service.js.map